version: "3.1"

services:
  joomla:
    image: joomla:3.9.12
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: joomlapass

  joomladb:
    image: mysql:5.6
    ports:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joomlapass
